# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginandreg', '0003_auto_20160819_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=1000)),
                ('travel_date_from', models.CharField(max_length=45)),
                ('travel_date_to', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrip', to='loginandreg.User')),
            ],
        ),
    ]
