# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
                ('mrManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
